### ISSUE TITLE
Ugly widget layout

### ISSUE THREAD

**Issue by xuchunyang** [zwz/emacs-ydcv#1]
I think when there is big enough frame `popup` should give us a rectangle, but it does not if using `ydcv.el`, for example

![2014-08-11 14 53 56](https://cloud.githubusercontent.com/assets/4550353/3872990/bf0fbaa2-2127-11e4-8293-ca4ae9d8bc85.png)

I try to use `popup-tip` to show Chinese text and it still has the same issue. I am not sure if we use `popup` correctly, or it is a bug of `popup` when dealing with non-English text?

**Comment by zwz** [comment]
I guess the issue is about how to treat Chinese characters and English characters, since they have different size. I am not sure if I am using popup-tip correctly, but this tool relies on it.
